In [1]:
from openpyxl import load_workbook
from openpyxl.chart import BarChart, Reference

In [3]:
# Read workbook and select sheet
wb = load_workbook('D:/Project/Data Sciences/pandas/14- Excel Report/pivot_table.xlsx')
ws = wb.active

In [4]:
ws.merge_cells("A1:D1")

In [1]:
var = '01234567'

In [2]:
var[::2]

'0246'

In [4]:
'1'+'2'

'12'

In [5]:
myvar = 'hello'
myvar.upper()

'HELLO'

In [11]:
L=[]
L.append(['a','b'])
L

[['a', 'b']]

In [12]:
Dict={"A":1,"B":"2","C":[3,3,3],"D":(4,4,4),'E':5,'F':6}

In [14]:
Dict["D"]

(4, 4, 4)

In [16]:
x=1

if(x!=1):
    print('Hello')

else:
    print('Hi')

print('Mike')

Hi
Mike


In [21]:
A = ['1','2','3']
A.sort()

for a in A:
    print(2*a)

11
22
33


In [18]:
# when will the function return a value of 1
def Delta(x):
    if x==0:
        y=1;
    else:
        y=0;
    return(y)

In [20]:
Delta(0)

1

In [22]:
with open("Example2.txt","w") as writefile:
    writefile.write("This is line A\n")
    writefile.write("This is line B\n")

In [24]:
with open("Example2.txt","r") as writefile:
    print(writefile.readlines())


['This is line A\n', 'This is line B\n']


In [26]:
with open("Example2.txt","a") as file1:
    print(file1.write("This is line C\n"))

15


In [28]:
import numpy as np
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [29]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [31]:
np.dot(a,b)

0

In [32]:
A='1234567'
A[1::2]

'246'

In [33]:
print("Hello\nWorld!")

Hello
World!


In [34]:
bool(1)

True

In [35]:
Numbers = "0123456"
# How would you obtain the even elements?
Numbers[::2]

'0246'

In [36]:
"0123456".find('1')

1

In [45]:
A=(0,1,2,3)
A[-1]

3

In [46]:
B=["a","b","c"]
B[1:]

['b', 'c']

In [57]:
age =20
if(age<=16):
    print("good")
elif(age==19):
    print("better")
else:
    print("not bad")
print("done")

not bad
done


In [59]:
x=3

y=1

while(y!=x):
    print(y)
    y=y+1

1
2


## What is for loop?  
- The for loop enables you to execute a code block multiple times. For example, you would use this if you would like to print out every element in a list.   
- Let's try to use a for loop to print all the years presented in the list dates:

The code in the indent is executed <code>N</code> times, each time the value of <code>i</code> is increased by 1 for every execution. The statement executed is to <code>print</code> out the value in the list at index <code>i</code> as shown here:

In [60]:
# For loop example

dates = [1982,1980,1973]
N = len(dates)

for i in range(N):
    print(dates[i])   

1982
1980
1973


<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%203/images/LoopsForRange.gif" width="800">


In [64]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [65]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [66]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

In [67]:
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [69]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])



In [62]:
a=1

def add(b):
    return a+b

c=add(10)
c

11

In [63]:
def f(*x):
    return sum(x)
f(12)

12