## Numpy

1. Write statement to import numpy ?

In [1]:
import numpy as np

2. create a single dimensional array

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

3. create a  multi- dimensional array

In [9]:
n3  =np.array([[10,20,34,54,23], [34,54,56,52,45]])
n3

array([[10, 20, 34, 54, 23],
       [34, 54, 56, 52, 45]])

4. Create an array of 10 random integers?

In [3]:
arr = np.random.randint(1, 100,5)
arr

array([44, 89, 75, 50, 90])

5. Create an array of elementas from 10-20?

In [4]:
arr= np.arange(100,2)
arr

array([], dtype=int32)

6. create an array which contains value 5, 10 times

In [5]:
arr2 = np.ones(5)*50
arr2

array([50., 50., 50., 50., 50.])

6. create a one dimensional array and convert that into 3*3 matrix

In [6]:
arr3 = np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Create an array and then convert all the even number with 0.

In [21]:
arr = np.arange(1,112)
arr[arr%2 ==0]=0
arr

array([  1,   0,   3,   0,   5,   0,   7,   0,   9,   0,  11,   0,  13,
         0,  15,   0,  17,   0,  19,   0,  21,   0,  23,   0,  25,   0,
        27,   0,  29,   0,  31,   0,  33,   0,  35,   0,  37,   0,  39,
         0,  41,   0,  43,   0,  45,   0,  47,   0,  49,   0,  51,   0,
        53,   0,  55,   0,  57,   0,  59,   0,  61,   0,  63,   0,  65,
         0,  67,   0,  69,   0,  71,   0,  73,   0,  75,   0,  77,   0,
        79,   0,  81,   0,  83,   0,  85,   0,  87,   0,  89,   0,  91,
         0,  93,   0,  95,   0,  97,   0,  99,   0, 101,   0, 103,   0,
       105,   0, 107,   0, 109,   0, 111])

8. Create a 2d array of size 3*#  but all the elements shold be betweeen 0 and 1.


In [23]:
arr = np.random.rand(9).reshape(3,3)
arr

array([[0.10864757, 0.68526683, 0.44381721],
       [0.34224407, 0.09843855, 0.8494018 ],
       [0.99055327, 0.29487739, 0.09356897]])

9. perform the slicing

In [27]:
arr = np.arange(1,17).reshape(4,4)
arr2 = arr[1:,1:3]
arr2

array([[ 6,  7],
       [10, 11],
       [14, 15]])

10. Concate 2D aarray horizontally and vertically.

In [29]:
arr = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)
np.hstack((arr,arr2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])