## Numpy

1. Write statement to import numpy ?

In [1]:
import numpy as np

2. create a single dimensional array

In [4]:
arr = np.array([1,2,3,4,5])


3. create a  multi- dimensional array

In [3]:
n3  =np.array([[10,20,34,54,23], [34,54,56,52,45]])
n3

array([[10, 20, 34, 54, 23],
       [34, 54, 56, 52, 45]])

4. Create an array of 10 random integers?

In [8]:
arr = np.random.randint(1, 100,10)
arr

array([25, 53, 42, 47, 46, 37, 68, 16, 18,  2])

5. Create an array of elementas from 10-20?

In [9]:
arr= np.arange(100,2)
arr

array([], dtype=int32)

6. create an array which contains value 5, 10 times

In [10]:
arr2 = np.ones(5)*50
arr2

array([50., 50., 50., 50., 50.])

6. create a one dimensional array and convert that into 3*3 matrix

In [11]:
arr3 = np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Create an array and then convert all the even number with 0.

In [21]:
arr = np.arange(1,112)
arr[arr%2 ==0]=0
arr

array([  1,   0,   3,   0,   5,   0,   7,   0,   9,   0,  11,   0,  13,
         0,  15,   0,  17,   0,  19,   0,  21,   0,  23,   0,  25,   0,
        27,   0,  29,   0,  31,   0,  33,   0,  35,   0,  37,   0,  39,
         0,  41,   0,  43,   0,  45,   0,  47,   0,  49,   0,  51,   0,
        53,   0,  55,   0,  57,   0,  59,   0,  61,   0,  63,   0,  65,
         0,  67,   0,  69,   0,  71,   0,  73,   0,  75,   0,  77,   0,
        79,   0,  81,   0,  83,   0,  85,   0,  87,   0,  89,   0,  91,
         0,  93,   0,  95,   0,  97,   0,  99,   0, 101,   0, 103,   0,
       105,   0, 107,   0, 109,   0, 111])

8. Create a 2d array of size 3*#  but all the elements shold be betweeen 0 and 1.


In [23]:
arr = np.random.rand(9).reshape(3,3)
arr

array([[0.10864757, 0.68526683, 0.44381721],
       [0.34224407, 0.09843855, 0.8494018 ],
       [0.99055327, 0.29487739, 0.09356897]])

9. perform the slicing

In [27]:
arr = np.arange(1,17).reshape(4,4)
arr2 = arr[1:,1:3]
arr2

array([[ 6,  7],
       [10, 11],
       [14, 15]])

10. Concate 2D aarray horizontally and vertically.

In [29]:
arr = np.arange(1,10).reshape(3,3)
arr2 = np.arange(10,19).reshape(3,3)
np.hstack((arr,arr2))

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

11 . Add two array variable 

In [28]:
arr_add = np.array([1,3,4,4])
arr_add1 = np.array([4,5,5,7])

In [30]:
sum_arr = np.add(arr_add,arr_add1)
sum_arr

array([ 5,  8,  9, 11])

In [35]:
np.save("S_a.py",arr)

Create a null vector of size 10

In [5]:
null_vactor = np.zeros(10)
null_vactor

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create Simple 1-D array and check type and check data types in array

In [6]:
null_vactor.dtype

dtype('float64')

Create Simple 1-D array and check type and check data types in array

In [7]:
null_vactor.ndim

1

In [9]:
null_vactor.itemsize

8

In [10]:
null_vactor.nbytes

80

Create a null vector of size 10 but the fifth value which is 1

In [11]:
null_vactor[4]=1
null_vactor

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Create a vector with values ranging from 10 to 49

In [13]:
vector = np.arange(10,49)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

Reverse a vector (first element becomes last)

In [14]:
np.flip(vector)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

Create a 13x3 matrix with values ranging from 10 to 48

In [43]:
vector.reshape(13,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39],
       [40, 41, 42],
       [43, 44, 45],
       [46, 47, 48]])

Create a 3x3 matrix with values ranging from 0 to 8

In [44]:
array = [1,2,0,0,4,0]
np.nonzero(array)

(array([0, 1, 4], dtype=int64),)

Create a 3x3 identity matrix

In [45]:
matrix = np.identity(3)
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 3x3x3 array with random values

In [47]:
np.random.random((3,3,3))

array([[[0.77447863, 0.62791172, 0.85807559],
        [0.28049417, 0.58543504, 0.41307389],
        [0.63867411, 0.80958295, 0.35258471]],

       [[0.17520748, 0.05381894, 0.43350791],
        [0.06286098, 0.57858728, 0.25200476],
        [0.54226851, 0.31138901, 0.78766146]],

       [[0.9887631 , 0.35261914, 0.13354007],
        [0.10759648, 0.82713279, 0.68917967],
        [0.73422556, 0.54428021, 0.85693708]]])

Create a 10x10 array with random values and find the minimum and maximum values

In [51]:
matrix = np.random.random((10,10))
print("Minimum Value :", matrix.min())
print("Maximum Value :", matrix.max())

Minimum Value : 0.00970546434374242
Maximum Value : 0.9996802100471817


Create a random vector of size 150 and find the mean value

In [53]:
vect = np.random.random(150)
vect.mean()

0.5006279781931365

Create a 2d array with 1 on the border and 0 inside

In [61]:
ar1 = np.ones((4,4))
ar1[1:3,1:3]=0
ar1

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

How to add a border (filled with 0's) around an existing array? 

In [63]:
ar1 =np.zeros((4,4))
ar1[1:3,1:3]=1
ar1

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [64]:
array = np.array([[ 1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("Accessing Element 13 : ", array[1,5])
print("First Row : ", array[0])
print("Third column : ", array[0,2])
print(array[0,1:6:2])
array[1,5] = 20
print("Replace Element 13 : ", array[1,5])

Accessing Element 13 :  13
First Row :  [1 2 3 4 5 6 7]
Third column :  3
[2 4 6]
Replace Element 13 :  20


In [68]:
np.append(np.repeat(1,3),np.tile(1,3))

array([1, 1, 1, 1, 1, 1])

show how Numpy taking less memory compared to Python List?

In [71]:
l = range(1000)
import sys
a = 10
print("Size of list : ", sys.getsizeof(a)*len(l))

sys.getsizeof(a)

Size of list :  28000


28